title: Raymond Lee
logo: /assets/img/logo.png
description: Hi! I'm Raymond, and I aspire to work in data science and analysis. Here is a list of my projects. Click on the title to learn more!
theme: jekyll-theme-minimal
